[package]
name = "rs-sitecrawler"
version = "0.1.0"
authors = ["Jonathan Pentecost <pentecostjonathan@gmail.com>"]

[dependencies]
hyper = "0.11"
hyper-tls = "0.1.2"
tokio-core = "0.1"
futures = "0.1"
